### ISSUE TITLE
Error while making outgoing call

### ISSUE THREAD

**Issue by naisanhamza88** [VoiSmart/pjsip-android#10]
I have this Error when make call after done register 

> SipService: Error while making outgoing call
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'net.gotev.sipservice.SipCall net.gotev.sipservice.SipAccount.addOutgoingCall(java.lang.String)' on a null object reference
                                                                          at net.gotev.sipservice.SipService.handleMakeCall(SipService.java:463)
                                                                          at net.gotev.sipservice.SipService.access$1100(SipService.java:67)
                                                                          at net.gotev.sipservice.SipService$2.run(SipService.java:136)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pookie13** [comment]
Hey naisanhamza88,
I am encountered with the same error. have you find the solution for that exception. if yes then please let me know how to solve it. for now, I am unable to find anything which is NUll. so please revert as soon as possible.

**Comment by roxane11** [comment]
Yes i see same error. Any solution guys?

**Comment by ashishsecrets** [comment]
Make sure the intent received in every SipCommand operation is int with default value 0 then cast it to string  Null pointer here means it's an empty intent. That's what I did to get mine working
