### ISSUE TITLE
Error while trying to unhold Incoming call

### ISSUE THREAD

**Issue by haraprasadsatapathy** [VoiSmart/pjsip-android#47]
E/SipCall: Error while trying to unhold call
    java.lang.Exception: Title:       pjsua_call_reinvite2(id, param.p_opt, param.p_msg_data)
    Code:        70013
    Description: Invalid operation (PJ_EINVALIDOP)
    Location:    ../src/pjsua2/call.cpp:515
    
        at org.pjsip.pjsua2.pjsua2JNI.Call_reinvite(Native Method)
        at org.pjsip.pjsua2.Call.reinvite(Call.java:123)
        at net.gotev.sipservice.SipCall.setHold(SipCall.java:313)
        at net.gotev.sipservice.SipCall.toggleHold(SipCall.java:324)
        at net.gotev.sipservice.SipService.handleToggleCallHold(SipService.java:318)
        at net.gotev.sipservice.SipService.access$2000(SipService.java:80)
        at net.gotev.sipservice.SipService$2.run(SipService.java:176)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by aenonGit** [comment]
tried with the latest? you using TCP or UDP protocol configured with account?

**Comment by aenonGit** [comment]
close due to inactivity
