### ISSUE TITLE
Error while toggling video transmission

### ISSUE THREAD

**Issue by dsvignesh** [VoiSmart/pjsip-android#66]
Hi, i am getting the below error
04-06 16:50:01.766 31836-31976/com.al.alvoip E/SipCall: Error while toggling video transmission
    java.lang.Exception: Title:       pjsua_call_set_vid_strm(id, op, &prm)
    Code:        70006
    Description: Not found (PJ_ENOTFOUND)
    Location:    ../src/pjsua2/call.cpp:633
    
        at org.pjsip.pjsua2.pjsua2JNI.Call_vidSetStream(Native Method)
        at org.pjsip.pjsua2.Call.vidSetStream(Call.java:171)
        at com.al.alvoip.sipservice.SipCall.setVideoMute(SipCall.java:539)
        at com.al.alvoip.sipservice.SipCall.onCallState(SipCall.java:123)
        at org.pjsip.pjsua2.pjsua2JNI.SwigDirector_Call_onCallState(pjsua2JNI.java:2424)

How to resolve, Please help us

**Comment by aenonGit** [comment]
that's a catched exception, nothing wrong with that. Do you experience any other weird behavior?

**Comment by dsvignesh** [comment]
Hi,
Video call is working fine.

That is configuration issue in sip server.

**Comment by aanalmehta-sa** [comment]
Hey, I am implementing video call and getting the same issue.
I have set 
my_cfg.accCfg.videoConfig?.autoTransmitOutgoing = true at time of initialization

I have also set 
val callSettings = prm.opt
        callSettings.audioCount = 1
        callSettings.videoCount = 1
at time of making call and answering call.

The issue I thought to be root cause is:
- When I run the above code, I am getting the same exception.
- I am not getting CallMediaInfo status pjsua_call_media_status.PJSUA_CALL_MEDIA_ACTIVE

Can you tell me if I am doing anything wrong?
We are using Asterisk server. Do we need to configure anything on server side?
For Audio calls, it is running well.

Thank you in advance!

**Comment by aenonGit** [comment]
on the server side the video codecs are enabled? What do you see in the sdp answer from the server?

**Comment by aanalmehta-sa** [comment]
I am getting this when I accept call:
 Using SIP RTP CoS mark 5
    -- Called SIP/204
    -- SIP/204-00000002 is ringing
    -- SIP/204-00000002 answered SIP/205-00000001

**Comment by aenonGit** [comment]
show me the sip trace with the sdp

**Comment by aanalmehta-sa** [comment]
Here are the logs:
```
v=0
o=- 3775803259 3775803259 IN IP4 192.168.0.140
s=pjmedia
b=AS:386
t=0 0
a=X-nat:0
m=audio 45539 RTP/AVP 98 97 99 104 3 0 8 9 113 114 115 116 117 18 120 96
c=IN IP4 192.168.0.140
b=TIAS:96000
a=rtcp:41318 IN IP4 192.168.0.140
a=sendrecv
a=rtpmap:98 speex/16000
a=rtpmap:97 speex/8000
a=rtpmap:99 speex/32000
a=rtpmap:104 iLBC/8000
a=fmtp:104 mode=30
a=rtpmap:3 GSM/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:113 G7221/16000
a=fmtp:113 bitrate=24000
a=rtpmap:114 G7221/16000
a=fmtp:114 bitrate=32000
a=rtpmap:115 G7221/32000
a=fmtp:115 bitrate=24000
a=rtpmap:116 G7221/32000
a=fmtp:116 bitrate=32000
a=rtpmap:117 G7221/32000
a=fmtp:117 bitrate=48000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:120 opus/48000/2
a=fmtp:120 useinbandfec=1
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-16
a=ice-ufrag:7c67908d
a=ice-pwd:5e87e0fe
a=candidate:Hc0a8008c 1 UDP 2130706431 192.168.0.140 45539 typ host
a=candidate:Hc0a8008c 2 UDP 2130706430 192.168.0.140 41318 typ host
m=video 38391 RTP/AVP 97
c=IN IP4 192.168.0.140
b=TIAS:256000
a=rtcp:47350 IN IP4 192.168.0.140
a=sendrecv
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42e01e; packetization-mode=1
a=ice-ufrag:42050176
a=ice-pwd:5942dbf8
a=candidate:Hc0a8008c 1 UDP 2130706431 192.168.0.140 38391 typ host
a=candidate:Hc0a8008c 2 UDP 2130706430 192.168.0.140 47350 typ host
<------------->
--- (16 headers 51 lines) ---
Sending to 192.168.0.140:6000 (no NAT)
Using INVITE request as basis request - 4cc21aef-b955-4ed7-bb4b-0371e60fd2f3
Found peer '204' for '204' from 192.168.0.140:6000
  == Using SIP VIDEO CoS mark 6
  == Using SIP RTP CoS mark 5
Found RTP audio format 98
Found RTP audio format 97
Found RTP audio format 99
Found RTP audio format 104
Found RTP audio format 3
Found RTP audio format 0
Found RTP audio format 8
Found RTP audio format 9
Found RTP audio format 113
Found RTP audio format 114
Found RTP audio format 115
Found RTP audio format 116
Found RTP audio format 117
Found RTP audio format 18
Found RTP audio format 120
Found RTP audio format 96
Found audio description format speex for ID 98
Found audio description format speex for ID 97
Found audio description format speex for ID 99
Found audio description format iLBC for ID 104
Found audio description format GSM for ID 3
Found audio description format PCMU for ID 0
Found audio description format PCMA for ID 8
Found audio description format G722 for ID 9
Found audio description format G7221 for ID 113
[Aug 26 18:54:13] WARNING[9761][C-00000009]: res_format_attr_siren7.c:54 siren7_parse_sdp_fmtp: Got Siren7 offer at 24000 bps, but only 32000 bps supported; ignoring.
Found audio description format G7221 for ID 114
Found audio description format G7221 for ID 115
[Aug 26 18:54:13] WARNING[9761][C-00000009]: res_format_attr_siren14.c:54 siren14_parse_sdp_fmtp: Got siren14 offer at 24000 bps, but only 48000 bps supported; ignoring.
Found audio description format G7221 for ID 116
[Aug 26 18:54:13] WARNING[9761][C-00000009]: res_format_attr_siren14.c:54 siren14_parse_sdp_fmtp: Got siren14 offer at 32000 bps, but only 48000 bps supported; ignoring.
Found audio description format G7221 for ID 117
Found audio description format G729 for ID 18
Found audio description format opus for ID 120
Found audio description format telephone-event for ID 96
Found RTP video format 97
Found video description format H264 for ID 97
Capabilities: us - (ulaw|alaw|speex|gsm|h261|h263|h263p), peer - audio=(ulaw|gsm|alaw|g722|g729|speex|speex16|speex32|ilbc|siren7|siren14|opus)/video=(h264)/text=(nothing), combined - (ulaw|alaw|speex|gsm)
Non-codec capabilities (dtmf): us - 0x1 (telephone-event|), peer - 0x1 (telephone-event|), combined - 0x1 (telephone-event|)
Peer audio RTP is at port 192.168.0.140:45539
Peer video RTP is at port 192.168.0.140:38391
Looking for 205 in incoming-calls (domain 192.168.2.99)
sip_route_dump: route/path hop: <sip:204@192.168.0.140:6000;ob>

<--- Transmitting (no NAT) to 192.168.0.140:6000 --->
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.0.140:6000;branch=z9hG4bKPj7b81844f-4317-4cfa-bda9-626dbd1178f9;received=192.168.0.140;rport=6000
From: sip:204@192.168.2.99;tag=919e1146-7c51-41a2-9190-540ede0d7c0f
To: sip:205@192.168.2.99
Call-ID: 4cc21aef-b955-4ed7-bb4b-0371e60fd2f3
CSeq: 8313 INVITE
Server: Asterisk PBX 13.27.1
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Session-Expires: 1800;refresher=uas
Contact: <sip:205@192.168.2.99:5060>
Content-Length: 0
```

Thank you so much :)

**Comment by aanalmehta-sa** [comment]
I feel it's issue with CallMediaInfo. I am receiving PJSUA_CALL_MEDIA_NONE.

**Comment by aenonGit** [comment]
that's the sdp of the INVITE you send to the server. But what does it reply? What's the 200OK?

**Comment by aanalmehta-sa** [comment]
@aenonGit 
Here it is:

```
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.0.110:5060;branch=z9hG4bKPjiXHEFs1cgwjypCRmLtut19teJfSbLMN4;received=192.168.0.110;rport=5060
From: sip:203@192.168.2.99;tag=S9V04qKi1y.UoEM9Yp-T-onOYNaUrutM
To: sip:209@192.168.2.99
Call-ID: -1V2FbPieN2WvjCR-CUPpCpY3vA34uGV
CSeq: 17335 INVITE
Server: Asterisk PBX 13.27.1
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Session-Expires: 1800;refresher=uas
Contact: <sip:209@192.168.2.99:5060>
Content-Length: 0


<------------>
    -- Executing [209@incoming-calls:1] Verbose("SIP/203-00000015", "2, sending notification") in new stack
  ==  sending notification
    -- Executing [209@incoming-calls:2] Verbose("SIP/203-00000015", "2, the extension is 209") in new stack
  ==  the extension is 209
    -- Executing [209@incoming-calls:3] Dial("SIP/203-00000015", "SIP/209,120") in new stack
[Aug 26 18:55:28] WARNING[10023][C-0000000b]: app_dial.c:2591 dial_exec_full: Unable to create channel of type 'SIP' (cause 20 - Subscriber absent)
  == Everyone is busy/congested at this time (1:0/0/1)
    -- Auto fallthrough, channel 'SIP/203-00000015' status is 'CHANUNAVAIL'

<--- Reliably Transmitting (no NAT) to 192.168.0.110:5060 --->
SIP/2.0 503 Service Unavailable
Via: SIP/2.0/UDP 192.168.0.110:5060;branch=z9hG4bKPjiXHEFs1cgwjypCRmLtut19teJfSbLMN4;received=192.168.0.110;rport=5060
From: sip:203@192.168.2.99;tag=S9V04qKi1y.UoEM9Yp-T-onOYNaUrutM
To: sip:209@192.168.2.99;tag=as0c57a7ec
Call-ID: -1V2FbPieN2WvjCR-CUPpCpY3vA34uGV
CSeq: 17335 INVITE
Server: Asterisk PBX 13.27.1
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Session-Expires: 1800;refresher=uas
X-Asterisk-HangupCause: Subscriber absent
X-Asterisk-HangupCauseCode: 20
Content-Length: 0


<------------>
Really destroying SIP dialog '537ee47f7ed200d616e6186f74db0812@127.0.1.1:5060' Method: INVITE

<--- SIP read from UDP:192.168.0.110:5060 --->
ACK sip:209@192.168.2.99 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.110:5060;rport;branch=z9hG4bKPjiXHEFs1cgwjypCRmLtut19teJfSbLMN4
Max-Forwards: 70
From: sip:203@192.168.2.99;tag=S9V04qKi1y.UoEM9Yp-T-onOYNaUrutM
To: sip:209@192.168.2.99;tag=as0c57a7ec
Call-ID: -1V2FbPieN2WvjCR-CUPpCpY3vA34uGV
CSeq: 17335 ACK
Content-Length: 0

<------------->
--- (8 headers 0 lines) ---
Really destroying SIP dialog '-1V2FbPieN2WvjCR-CUPpCpY3vA34uGV' Method: ACK
Reliably Transmitting (no NAT) to 192.168.0.140:6000:
OPTIONS sip:204@192.168.0.140:6000;ob SIP/2.0
Via: SIP/2.0/UDP 192.168.2.99:5060;branch=z9hG4bK606cb2a7
Max-Forwards: 70
From: "asterisk" <sip:asterisk@192.168.2.99>;tag=as79f93b6f
To: <sip:204@192.168.0.140:6000;ob>
Contact: <sip:asterisk@192.168.2.99:5060>
Call-ID: 2db63333176179a3070581d6473631f2@192.168.2.99:5060
CSeq: 102 OPTIONS
User-Agent: Asterisk PBX 13.27.1
Date: Mon, 26 Aug 2019 13:25:29 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0


---

<--- SIP read from UDP:192.168.0.140:6000 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.2.99:5060;received=192.168.2.99;branch=z9hG4bK606cb2a7
Call-ID: 2db63333176179a3070581d6473631f2@192.168.2.99:5060
From: "asterisk" <sip:asterisk@192.168.2.99>;tag=as79f93b6f
To: <sip:204@192.168.0.140;ob>;tag=z9hG4bK606cb2a7
CSeq: 102 OPTIONS
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Accept: application/sdp, application/pidf+xml, application/xpidf+xml, application/simple-message-summary, message/sipfrag;version=2.0, application/im-iscomposing+xml, text/plain
Supported: replaces, 100rel, timer, norefersub
Allow-Events: presence, message-summary, refer
User-Agent: Pjsua2 Android 2.6
Content-Length: 0

<------------->
--- (12 headers 0 lines) ---
Really destroying SIP dialog '2db63333176179a3070581d6473631f2@192.168.2.99:5060' Method: OPTIONS
Reliably Transmitting (no NAT) to 192.168.0.102:42788:
OPTIONS sip:209@192.168.0.102:42788;app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=ceoIl-yOQis:APA91bFUckxWCasOzZRSVi-3Nm6bVbwqabfqmKBs5ifTJRijEZYx0EqBjbiRu_lo5dhJwk1XpOWXQtIHirjAbproyAX5CzxYTSQTqdC5XsCURiKiQd2nthjbFTIjl8ZJdtYneX4FUjv_;pn-silent=1;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.2.99:5060;branch=z9hG4bK180f39d2
Max-Forwards: 70
From: "asterisk" <sip:asterisk@192.168.2.99>;tag=as6117a4da
To: <sip:209@192.168.0.102:42788;app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=ceoIl-yOQis:APA91bFUckxWCasOzZRSVi-3Nm6bVbwqabfqmKBs5ifTJRijEZYx0EqBjbiRu_lo5dhJwk1XpOWXQtIHirjAbproyAX5CzxYTSQTqdC5XsCURiKiQd2nthjbFTIjl8ZJdtYneX4FUjv_;pn-silent=1;transport=udp>
Contact: <sip:asterisk@192.168.2.99:5060>
Call-ID: 2c406d6c6a7bba903761c89c06d8f237@192.168.2.99:5060
CSeq: 102 OPTIONS
User-Agent: Asterisk PBX 13.27.1
Date: Mon, 26 Aug 2019 13:25:29 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0


---
Retransmitting #1 (no NAT) to 192.168.0.102:42788:
OPTIONS sip:209@192.168.0.102:42788;app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=ceoIl-yOQis:APA91bFUckxWCasOzZRSVi-3Nm6bVbwqabfqmKBs5ifTJRijEZYx0EqBjbiRu_lo5dhJwk1XpOWXQtIHirjAbproyAX5CzxYTSQTqdC5XsCURiKiQd2nthjbFTIjl8ZJdtYneX4FUjv_;pn-silent=1;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.2.99:5060;branch=z9hG4bK180f39d2
Max-Forwards: 70
From: "asterisk" <sip:asterisk@192.168.2.99>;tag=as6117a4da
To: <sip:209@192.168.0.102:42788;app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=ceoIl-yOQis:APA91bFUckxWCasOzZRSVi-3Nm6bVbwqabfqmKBs5ifTJRijEZYx0EqBjbiRu_lo5dhJwk1XpOWXQtIHirjAbproyAX5CzxYTSQTqdC5XsCURiKiQd2nthjbFTIjl8ZJdtYneX4FUjv_;pn-silent=1;transport=udp>
Contact: <sip:asterisk@192.168.2.99:5060>
Call-ID: 2c406d6c6a7bba903761c89c06d8f237@192.168.2.99:5060
CSeq: 102 OPTIONS
User-Agent: Asterisk PBX 13.27.1
Date: Mon, 26 Aug 2019 13:25:29 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0
```
Sometimes I saw service Unavailable and then I receive 200 OK.

**Comment by aenonGit** [comment]
ok, but either you send me the whole trace or nothing at all :P. I need the body (sdp) when there is one (i.e. the answer after your invite)

**Comment by ck505778675** [comment]
> Hi,
> Video call is working fine.
> 
> That is configuration issue in sip server.

how to deal,thanks !
