### ISSUE TITLE
no static method "Lorg/pjsip/pjsua2/pjsua2JNI;.SwigDirector_Buddy_onBuddyEvSubState(Lorg/pjsip/pjsua2/Buddy;J)V"

### ISSUE THREAD

**Issue by cmendes0101** [VoiSmart/pjsip-android#67]
When attempting to create the new endpoint, I get a crash of 

`
2019-04-15 11:03:12.110 29447-29478/com.package.id E/AndroidRuntime: FATAL EXCEPTION: SipService
    Process: com.package.id, PID: 29447
    java.lang.NoSuchMethodError: no static method "Lorg/pjsip/pjsua2/pjsua2JNI;.SwigDirector_Buddy_onBuddyEvSubState(Lorg/pjsip/pjsua2/Buddy;J)V"
        at org.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
        at org.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2507)
        at org.pjsip.pjsua2.pjsua2JNI.new_Endpoint(Native Method)
        at org.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:68)
        at net.gotev.sipservice.SipService.startStack(SipService.java:639)
        at net.gotev.sipservice.SipService.addAccount(SipService.java:882)
        at net.gotev.sipservice.SipService.handleSetAccount(SipService.java:589)
        at net.gotev.sipservice.SipService.access$500(SipService.java:46)
        at net.gotev.sipservice.SipService$2.run(SipService.java:102)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
`

Currently, I'm using built PJSIP libraries in jniLibs since when I was just including this library I would hit the error:
`
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.package.id-FMqWIT5j_VO_G54_AqyqmA==/lib/x86/libopenh264.so" has text relocations
`

Is there any additional configuration needed in the project?

**Comment by danms07** [comment]
How did you solved it?

**Comment by cmendes0101** [comment]
Honestly, don't remember totally. It was my fault since I had built the libraries to include but I didn't copy over some of the generated pjsip service files. 

If you're using the prebuilt libraries you most likely shouldn't hit this

**Comment by vruttimeghinfosol** [comment]
Please, If you've solved, tell me answer...

**Comment by shooding** [comment]
Don't just copy .so after build pjproject.
You should also copy <pjproject-build-output-folder>/pjsip-apps/src/swig/java/android/pjsua2/src/main/java/org/pjsip folder
to your App source folder.
