### ISSUE TITLE
Sample application based on this SIPService. How to use this ?

### ISSUE THREAD

**Issue by zackbugti** [VoiSmart/pjsip-android#85]
I have downloaded this and built, but it isn't running and I am facing difficulty understanding the code. So please somebody help me out how to make an application based on this. I need to develop just a simple application that could send/receive messages and calls. Please help me out somebody.

**Comment by rrymm** [comment]
Hi zackbugti 
I am also looking for any supporting information “how to start” or simple demo app.
Cheers.

**Comment by janolaskar** [comment]
Any update for this thread anyone??

**Comment by shadowwalkersteam** [comment]
Any sample app??

**Comment by jackkum** [comment]
```java
SipAccountData sipAccount = new SipAccountData();
SipServiceCommand.setEncryption(appContext, true, "alias");
// identifer of current call
int callId;
// identifer of current account
String accountId;

BroadcastEventReceiver event = new BroadcastEventReceiver(){
  @Override
  public void onStackStatus(boolean started) {
      if( ! started) {
          // something went wrong
      }
  }

  @Override
  public void onRegistration(String accountID, pjsip_status_code registrationStateCode) {
      if (registrationStateCode == pjsip_status_code.PJSIP_SC_OK) {
        Uri sipUri = Uri.parse(String.format("sip:%d@%s:%d", sipPayload.getCallId(), sipAccount.getHost(), sipAccount.getPort()));
        SipServiceCommand.makeCall(appContext, accountId, sipUri.toString());
      }
  }

  @Override
  public void onCallState(String accountID, int callID, pjsip_inv_state callStateCode, pjsip_status_code callStatusCode,
            long connectTimestamp, boolean isLocalHold, boolean isLocalMute, boolean isLocalVideoMute) {

      if(callStateCode == pjsip_inv_state.PJSIP_INV_STATE_CALLING){
          // current outgoing call
          callId = callID;
      }

      if(callStateCode == pjsip_inv_state.PJSIP_INV_STATE_DISCONNECTED){
          // end of call
      }
  }
});

// register events
event.register(appContext);
// init account 
sipAccount.setHost(sipPayload.getHost())
      .setPort(sipPayload.getPort())
      .setTcpTransport(true)
      .setUsername(sipPayload.getUser())
      .setPassword(sipPayload.getPassword())
      .setRealm(sipPayload.getHost())
      .setContactUriParams("")
;
// add account to the service
accountId = SipServiceCommand.setAccount(appContext, sipAccount);

...

// after end, unregister event
event.unregister(appContext);
```

**Comment by shadowwalkersteam** [comment]
what is the format to dial a number or to make a call? I was using sip:#####@server_address
But this is not working

**Comment by jackkum** [comment]
I have asterisk sip server with user context `client`, so dialplan for this user looks like that:
```
[client]
; ${EXTEN} here is a sipPayload.getCallId() from sip:1000@server:port
exten => _X.,1,SomeWorkWith(${EXTEN})
exten => _X.,2,MeetMe(${ROOM})
```

If you want to dial some phone number you should configure that on your sip server.
Asterisk dialplan should be looks like that:
```
[client_context]
exten => _X.,1,SomeCheckExten(${EXTEN})
exten => _X.,2,Dial(SIP/CHANNEL_THROUGH/EXTEN)
; or dial some sip user
; exten => _X.,2,Dial(SIP/USER/USER)
```

**Comment by SachithKasthuriarachchi** [comment]
Hi, can somebody please provide a sample code for making an call in android?  When I tried it gave me the following error.

`I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
W/AudioTrack: createTrack_l(-1): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 1280
I/AudioTrack: Need throttle time for OpenSLES player
W/libOpenSLES: Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
D/AudioRecord: openRecord_l() remove fast or raw flag of voip calls, source=7, flags=5
W/System.err: java.lang.Exception: Title:       pjsua_call_make_call(acc.getId(), &pj_dst_uri, param.p_opt, this, param.p_msg_data, &id)
W/System.err: Code:        70018
    Description: gethostbyname() has returned error (PJ_ERESOLVE)
    Location:    ../src/pjsua2/call.cpp:566
W/System.err:     at org.pjsip.pjsua2.pjsua2JNI.Call_makeCall(Native Method)
W/System.err:     at org.pjsip.pjsua2.Call.makeCall(Call.java:107)
        at com.ptt_app.easytalk.core.IPCall.makeCall(IPCall.java:488)
W/System.err:     at com.ptt_app.easytalk.core.IPAccount.addOutgoingCall(IPAccount.java:86)
W/System.err:     at com.ptt_app.easytalk.core.IPService.handleMakeCall(IPService.java:560)
W/System.err:     at com.ptt_app.easytalk.core.IPService.access$800(IPService.java:95)
W/System.err:     at com.ptt_app.easytalk.core.IPService$2.run(IPService.java:163)
        at android.os.Handler.handleCallback(Handler.java:883)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/System.out: [IPAccount] Error while making outgoing calljava.lang.Exception: Title:       pjsua_call_make_call(acc.getId(), &pj_dst_uri, param.p_opt, this, param.p_msg_data, &id)
    Code:        70018
    Description: gethostbyname() has returned error (PJ_ERESOLVE)
    Location:    ../src/pjsua2/call.cpp:566
I/System.out: [IPService]Error while making outgoing calljava.lang.NullPointerException: Attempt to invoke virtual method 'void com.ptt_app.easytalk.core.IPCall.setVideoParams(boolean, boolean)' on a null object reference
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ptt_app.easytalk.core.IPCall.setVideoParams(boolean, boolean)' on a null object reference
W/System.err:     at com.ptt_app.easytalk.core.IPService.handleMakeCall(IPService.java:561)
        at com.ptt_app.easytalk.core.IPService.access$800(IPService.java:95)
        at com.ptt_app.easytalk.core.IPService$2.run(IPService.java:163)
        at android.os.Handler.handleCallback(Handler.java:883)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/: PlayerBase::stop() from IPlayer
D/AudioTrack: stop(554): called with 16640 frames delivered`

**Comment by SachithKasthuriarachchi** [comment]
How to identify the incoming calls?

**Comment by fengfeilong0529** [comment]
A simple sample project can see [Here](https://github.com/fengfeilong0529/PjsipGo).
Just replace the sip configuration with your own

**Comment by SachithKasthuriarachchi** [comment]
Thank you very much!
