### ISSUE TITLE
NoSuchMethodError: no static method "Lorg/pjsip/pjsua2/pjsua2JNI;.SwigDirector_Call_onCreateMediaTransportSrtp(Lorg/pjsip/pjsua2/Call;J)V"

### ISSUE THREAD

**Issue by jackkum** [VoiSmart/pjsip-android#95]
Hello!
Trying to make a simple call, but something went wrong.

Add this lib as mentioned [here](https://github.com/VoiSmart/pjsip-android/issues/60#issuecomment-471535754) 

My code:
```java
// withouth this i got exception like: "alias could not be empty"
SipServiceCommand.setEncryption(appContext, true, "alias");

String accountId;
SipAccountData mSipAccount       = new SipAccountData();
BroadcastEventReceiver sipEvents = new BroadcastEventReceiver() {
  @Override
  public void onRegistration(String accountID, pjsip_status_code registrationStateCode) {
  if (registrationStateCode == pjsip_status_code.PJSIP_SC_OK) {
    SipServiceCommand.makeCall(appContext, accountId, "anyway");
  }
}

  @Override
  public void onReceivedCodecPriorities(ArrayList<CodecPriority> codecPriorities) {
    for (CodecPriority codec : codecPriorities) {
      if (codec.getCodecName().startsWith("PCM")) {
         codec.setPriority(CodecPriority.PRIORITY_MAX);
       } else {
         codec.setPriority(CodecPriority.PRIORITY_DISABLED);
       }
     }
    
    SipServiceCommand.setCodecPriorities(appContext, codecPriorities);
  }
};

mSipAccount.setHost(domain)
                .setPort(port)
                .setUsername(username)
                .setPassword(password)
                .setRealm(domain)
                .setContactUriParams("")
        ;

sipEvents.register(appContext);
accountId = SipServiceCommand.setAccount(ctx, mSipAccount);
SipServiceCommand.getCodecPriorities(ctx);
```

And i got exception bellow
```
java.lang.NoSuchMethodError: no static method "Lorg/pjsip/pjsua2/pjsua2JNI;.SwigDirector_Call_onCreateMediaTransportSrtp(Lorg/pjsip/pjsua2/Call;J)V"
        at org.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
        at org.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2398)
        at org.pjsip.pjsua2.pjsua2JNI.new_Endpoint(Native Method)
        at org.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:68)
        at net.gotev.sipservice.SipService.startStack(SipService.java:631)
        at net.gotev.sipservice.SipService.addAccount(SipService.java:875)
        at net.gotev.sipservice.SipService.handleSetAccount(SipService.java:581)
        at net.gotev.sipservice.SipService.access$600(SipService.java:42)
        at net.gotev.sipservice.SipService$2.run(SipService.java:94)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

Google tell me what method onCreateMediaTransportSrtp() is deprecated, may be this is trouble?

**Comment by jackkum** [comment]
Downgrade to 2.0.0 tag resolve the problem.
